fix nexus_location test
mayadata-io/mayastor-e2e pull request #325
Opened 2021-11-02 10:21 UTC by payes

Signed-off-by: Payes Anand <payes.anand@mayadata.io>

2021-11-02 10:57 UTC, blaisedias requested changes

2021-11-02 10:57 UTC, blaisedias commented on src/nexus_location/nexus_location_test.go
> +
If we are scheduling the pod on the master node, we should first assert that a pod can run on the master node using a SC without local set to true.
Only then proceed with the test for using a SC with local set to true.
Otherwise we run the risk of masking failures - if any.
Please add a log statement indicating which node the pod is scheduled on.

2021-11-02 14:41 UTC, payes commented on src/nexus_location/nexus_location_test.go
> +
Fixed, can you please take another look.

2021-11-02 17:37 UTC, blaisedias approved these changes

2021-11-03 05:18 UTC, rohan2794 approved these changes

2021-11-03 14:38 UTC, payes commented
bors merge

2021-11-12 11:51 UTC, blaisedias commented
bors merge

2021-11-12 12:21 UTC, merged