Test director secrets pr
mayadata-io/mayastor-e2e pull request #327
Opened 2021-11-02 14:15 UTC by milanhajek

2021-11-03 07:09 UTC, chriswldenyer approved these changes
LGTM

2021-11-04 10:54 UTC, chriswldenyer requested changes
Just remove the use of test_director_secret.yaml

2021-11-04 10:54 UTC, chriswldenyer commented on src/tools/extended-test-framework/scripts/deploy.sh
> +  kubectl delete -f ${DEPLOYDIR}/test_director/test_director_secret.yaml
We should remove this line as we won't be creating the secret this way. We can assume the secret is already created on the cluster.

2021-11-04 10:54 UTC, chriswldenyer commented on src/tools/extended-test-framework/scripts/deploy.sh
> +  kubectl create -f ${DEPLOYDIR}/test_director/test_director_secret.yaml
Also this line.

2021-11-04 11:20 UTC, chriswldenyer approved these changes
LGTM

2021-11-08 22:41 UTC, payes approved these changes
LGTM

2021-11-09 07:07 UTC, chriswldenyer approved these changes
LGTM

2021-11-09 07:19 UTC, merged