chore: fix restart logic
mayadata-io/mayastor-e2e pull request #346
Opened 2021-11-10 16:22 UTC by blaisedias

Use time dependency instead of name changes to
check if pods have been restarted.

This allows us to restart and check pods belonging
to deamonsets, deployments and statefulsets

2021-11-10 16:40 UTC, chriswldenyer approved these changes
Approved, but possibly one issue.

2021-11-10 16:40 UTC, chriswldenyer commented on src/common/k8stest/util_testpods.go
>  			if len(podNames) <= len(newPodNames) {
Extreme Nit: len(newPodNames) >=  len(podNames)  seems a clearer order to me.
We are waiting for the new pods to reach the number of the old pods.

2021-11-10 16:40 UTC, chriswldenyer commented on src/common/k8stest/util_testpods.go
>  		if err == nil {
Is this logic right?
The old code had err != nil before the "Restarting failed" error message

2021-11-11 05:13 UTC, payes approved these changes
LGTM

2021-11-15 12:05 UTC, blaisedias commented on src/common/k8stest/util_testpods.go
>  		if err == nil {
Oooh, good catch.

2021-11-15 12:11 UTC, blaisedias commented on src/common/k8stest/util_testpods.go
>  		if err == nil {
fixed https://github.com/mayadata-io/mayastor-e2e/pull/346/commits/a18a163ac8bd61a2a5bbd12c9e07a9675a8b81f3

2021-11-15 12:11 UTC, blaisedias commented on src/common/k8stest/util_testpods.go
>  			if len(podNames) <= len(newPodNames) {
fixed: https://github.com/mayadata-io/mayastor-e2e/pull/346/commits/a18a163ac8bd61a2a5bbd12c9e07a9675a8b81f3

2021-11-15 12:48 UTC, chriswldenyer requested changes
Looks like one change needed.

2021-11-15 12:48 UTC, chriswldenyer commented on src/common/k8stest/util_testpods.go
> +			if len(newPodNames) <= len(podNames) {
... and change "<=" to ">="
:-)

2021-11-15 12:48 UTC, chriswldenyer commented on src/common/k8stest/util_testpods.go
>  			err = CheckTestPodsHealth(common.NSMayastor())
So we check resources if restartMayastor() failed?

2021-11-15 12:52 UTC, blaisedias commented on src/common/k8stest/util_testpods.go
>  			err = CheckTestPodsHealth(common.NSMayastor())
Hmm.... the email shows things the wrong way around.
Confused me
line 570 is `if err = nil {` so we do resource check only if all preceding tests did not return an error.

2021-11-15 13:24 UTC, chriswldenyer approved these changes
LGTM

2021-11-15 13:24 UTC, chriswldenyer commented on src/common/k8stest/util_testpods.go
>  			err = CheckTestPodsHealth(common.NSMayastor())
That's weird, it looks OK if you look at the changes as a whole.

2021-11-15 13:47 UTC, chriswldenyer approved these changes
LGTM

2021-11-15 14:10 UTC, payes approved these changes
LGTM

2021-11-15 14:47 UTC, blaisedias commented
bors merge

2021-11-15 15:14 UTC, blaisedias commented
bors merge

2021-11-15 15:45 UTC, merged