test(e2e): add test to check volume stop serving I/O if a replica is faulted
mayadata-io/mayastor-e2e pull request #374
Opened 2021-11-30 08:57 UTC by w3aman

Signed-off-by: w3aman <aman.gupta@mayadata.io>

2022-01-04 11:36 UTC, blaisedias commented
The PR title and commit should mention MQ-2307

2022-01-04 12:59 UTC, payes commented
bors try

2022-01-04 13:30 UTC, payes commented
bors try

2022-01-05 07:44 UTC, rohan2794 approved these changes

2022-01-05 08:33 UTC, chriswldenyer requested changes
Generally OK but quite a lot of redundant code.

2022-01-05 08:33 UTC, chriswldenyer commented on src/node_replica_failure/utils.go
> +	// Create the volume with 1 replica
I'm not sure this comment is valid, the replica could depends on the sc, and when it is called the sc specifies 2 replicas IIUI?

2022-01-05 08:33 UTC, chriswldenyer commented on src/node_replica_failure/utils.go
> +func (c *inaccessibleEtcdTestConfig) createFioPod(verify bool) {
This is always called with verify false, so you could remove that logic.

2022-01-05 08:33 UTC, chriswldenyer commented on src/node_replica_failure/utils.go
> +	"--do_verify=0",
I think you should remove the --do_verify=0. I added that in my code because I wanted to separate out the verification phase in a separate fio run and turn off verification in this run configuration.
In your case it would be useful to allow verification to run at the end IMO to catch verification errors as well.
FYI it will make the run slightly longer.

2022-01-05 08:33 UTC, chriswldenyer commented on src/node_replica_failure/utils.go
> +func DisablePoolDeviceAtNode(nodeName string, device string, delaySecs int) {
It looks like delaySecs is always zero so you can remove that logic.

2022-01-05 08:33 UTC, chriswldenyer commented on src/node_replica_failure/utils.go
> +func EnablePoolDeviceAtNode(nodeName string, device string, delaySecs int) {
It looks like delaySecs is always zero so you can remove that logic.

2022-01-06 09:50 UTC, payes commented on src/node_replica_failure/utils.go
> +	// Create the volume with 1 replica
resolved

2022-01-06 10:25 UTC, chriswldenyer approved these changes
LGTM

2022-01-07 08:56 UTC, payes commented
bors try

2022-01-07 16:59 UTC, payes commented
bors try

2022-01-11 16:12 UTC, blaisedias approved these changes

2022-01-11 19:17 UTC, payes commented
bors merge

2022-01-11 19:24 UTC, payes commented
bors merge

2022-01-11 19:57 UTC, merged