(etfw) MQ-2458 log monitor poc
mayadata-io/mayastor-e2e pull request #382
Opened 2021-12-03 14:38 UTC by milanhajek

2021-12-06 15:22 UTC, chriswldenyer commented on src/tools/extended-test-framework/log_monitor/cmd/main/log_checker.go
> +	p, err := GetPod("test-director", "mayastor-e2e")
The go-swagger code-generator can generate client code to handle a lot of this.
Was there a reason for not using generated code?
See extended-test-framework/common/test_director_lib.go

2021-12-13 11:05 UTC, chriswldenyer approved these changes
LGTM

2022-01-04 07:06 UTC, rohan2794 commented on src/tools/extended-test-framework/deploy/log_monitor/elastic_kibana/monitoring_namespace.yaml
> +  name: monitoring
are we using this namespace ?

2022-01-04 07:25 UTC, rohan2794 commented on src/tools/extended-test-framework/log_monitor/docker/Dockerfile
> +#COPY config-local.yaml /config/config-local.yaml
Comment seems confusing, if not relevant please remove it

2022-01-04 13:47 UTC, milanhajek commented on src/tools/extended-test-framework/deploy/log_monitor/elastic_kibana/monitoring_namespace.yaml
> +  name: monitoring
Not now. It was prepared with PoC for testing purposes. It could be removed, but I want to keep it just for future purposes.

2022-01-04 13:51 UTC, milanhajek commented on src/tools/extended-test-framework/log_monitor/docker/Dockerfile
> +#COPY config-local.yaml /config/config-local.yaml
Done

2022-01-05 07:38 UTC, rohan2794 approved these changes

2022-01-10 08:34 UTC, chriswldenyer requested changes
It looks like there are some issues with the paths in the scripts.

2022-01-10 08:34 UTC, chriswldenyer commented on src/tools/extended-test-framework/scripts/build.sh
> +pushd ../log_monitoring/scripts && ./build.sh; popd
```suggestion
pushd ../log_monitor/scripts && ./build.sh; popd
```
Looks like this change is needed for build.sh

2022-01-10 08:34 UTC, chriswldenyer commented on src/tools/extended-test-framework/scripts/deploy.sh
> +  kubectl delete -f ${DEPLOYDIR}/log-monitor/log_monitor.yaml
It looks like these (lines 126-138) all need log_monitor (i.e. underscore in the path)

2022-01-17 14:31 UTC, chriswldenyer requested changes
I had problems running this as it is written.  The suggested changes seem to fix it.
There are also some pkg files (extended-test-framework/pkg/...) that were checked in by mistake, so need to be removed from this PR.

2022-02-11 13:47 UTC, chriswldenyer requested changes
You still need to remove the pkg files from the PR, otherwise OK I think.

2022-02-14 12:10 UTC, milanhajek commented
bors merge

2022-02-14 12:11 UTC, milanhajek commented
bors merge

2022-02-14 12:42 UTC, merged