refactor: remove assert from common code (src/comon/k8stest/util.go)
mayadata-io/mayastor-e2e pull request #424
Opened 2022-01-28 04:41 UTC by rohan2794

JIRA: https://mayadata.atlassian.net/browse/MQ-2747

2022-01-28 04:51 UTC, rohan2794 commented
bors try

2022-01-28 11:17 UTC, rohan2794 commented
bors try

2022-01-28 13:49 UTC, rohan2794 commented
bors try

2022-01-31 05:31 UTC, rohan2794 commented
bors try

2022-02-02 04:38 UTC, rohan2794 commented
bors try

2022-02-02 07:56 UTC, chriswldenyer requested changes
LGTM except I think the channel length should be > 1

2022-02-02 07:56 UTC, chriswldenyer commented on src/common/k8sinstall/util.go
> +	errors := make(chan error, 1)
I think you will need to change 1 to len(mayastorYamlFiles) here, the number sets the buffer size in the channel and if more than one thread writes to the channel, the second thread will block, if the length is one.
Also on line 231.

2022-02-02 07:56 UTC, chriswldenyer commented on src/common/k8stest/util_e2e_agent.go
> +		return ready
suggestion: maybe explicitly return false here?

2022-02-02 09:26 UTC, rohan2794 commented on src/common/k8stest/util_e2e_agent.go
> +		return ready
Done

2022-02-02 09:26 UTC, rohan2794 commented on src/common/k8sinstall/util.go
> +	errors := make(chan error, 1)
Done

2022-02-02 10:20 UTC, chriswldenyer approved these changes
LGTM

2022-02-07 08:35 UTC, payes approved these changes

2022-02-07 08:36 UTC, rohan2794 commented
bors merge

2022-02-07 09:08 UTC, merged