refactor: remove assert from node label and unlabel functions
mayadata-io/mayastor-e2e pull request #430
Opened 2022-02-08 14:06 UTC by rohan2794

JIRA: https://mayadata.atlassian.net/browse/MQ-2760

2022-02-08 14:08 UTC, rohan2794 commented
bors try

2022-02-09 07:45 UTC, chriswldenyer approved these changes
LGTM, one suggestion

2022-02-09 07:45 UTC, chriswldenyer commented on src/common/k8stest/util_pod.go
> +			time.Sleep(common.TimeSleepSecs * time.Second)
If this is likely to pass first time, maybe it's worth moving the sleep to the end of the loop to speed up the test.
The same applies to other places where this pattern is used.

2022-02-09 10:50 UTC, blaisedias requested changes

2022-02-09 10:50 UTC, blaisedias commented on src/common/constants.go
> +const Timeout = 300      // timeout in seconds
This value is only used in one function, so rather than declaring a global it would be better to declare it within that function itself. Also I think timeout values differ for different operations so a global values isn't that useful.

2022-02-09 10:50 UTC, blaisedias commented on src/common/constants.go
> +const TimeSleepSecs = 10 // sleep time in seconds
Similarly polling time depends on the operation, so maybe defining a global sleep time isn't the way to go.

2022-02-09 10:50 UTC, blaisedias commented on src/common/k8stest/util_pod.go
> +	var errors common.ErrorAccumulator
We shouldn't accumulate errors, just return the last error - if any - that matches the semantics of the Eventually

2022-02-09 12:15 UTC, rohan2794 commented on src/common/constants.go
> +const TimeSleepSecs = 10 // sleep time in seconds
Done

2022-02-09 12:15 UTC, rohan2794 commented on src/common/constants.go
> +const Timeout = 300      // timeout in seconds
Done

2022-02-09 12:15 UTC, rohan2794 commented on src/common/k8stest/util_pod.go
> +			time.Sleep(common.TimeSleepSecs * time.Second)
Done

2022-02-09 12:15 UTC, rohan2794 commented
bors try

2022-02-09 13:50 UTC, blaisedias commented on src/common/k8stest/mayastor_check.go
> +const sleepTieSec = 10 // sleep time in seconds
typo?

2022-02-09 13:50 UTC, blaisedias commented on src/common/k8stest/util_pod.go
>  			nodeList, err := GetNodeListForPods("app="+label, namespace)
Declare nodeList as a var and assign using `=`  instead of `:=`

2022-02-09 13:52 UTC, rohan2794 commented on src/common/k8stest/util_pod.go
>  			nodeList, err := GetNodeListForPods("app="+label, namespace)
pushed the changes https://github.com/mayadata-io/mayastor-e2e/pull/430/commits/52cf54cfdf9f8e64cd5aa7969f8017f7f6b2702f

2022-02-09 13:55 UTC, rohan2794 commented on src/common/k8stest/mayastor_check.go
> +const sleepTieSec = 10 // sleep time in seconds
Done

2022-02-09 14:59 UTC, blaisedias approved these changes

2022-02-10 07:35 UTC, chriswldenyer approved these changes
LGTM

2022-02-10 08:03 UTC, rohan2794 commented
bors merge

2022-02-10 11:16 UTC, rohan2794 commented
bors merge

2022-02-10 11:55 UTC, merged