test(etfw): add primitive pool deletion test to etfw
mayadata-io/mayastor-e2e pull request #443
Opened 2022-02-24 06:15 UTC by rohan2794

JIRA: https://mayadata.atlassian.net/browse/MQ-2795

2022-02-24 07:57 UTC, chriswldenyer requested changes
Cool! Thanks for doing this so quickly. A few changes needed I think. 
Also please add the test to the "choice" parameter in Mayastor-e2e-etfw-test/Jenkinsfile so we can run it in the mayastor-e2e-etfw-test pipeline.

2022-02-24 07:57 UTC, chriswldenyer commented on src/tools/extended-test-framework/deploy/test_conductor/test_conductor_pod.yaml.template
> +      image: ci-registry.mayastor-ci.mayadata.io/mayadata/test_conductor_${TEST}:exp
This should be switched back to "latest" for now. I hope to put in a PR soon to make this configurable at run-time.

2022-02-24 07:57 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	if err != nil {
I don't think this detects that len(replicas) != replicaCount when the timeout is exceeded.

2022-02-24 07:57 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +		return fmt.Errorf("failed to get mayastor pool usage in cluster, error: %v", err)
Also I don't think this will detect that pool usage is not zero here. I think this is true in other places in the function.

2022-02-24 07:57 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +
I think you should put some comments in this function at each stage to describe what is being tested and what the expected outcome is.

2022-02-24 07:57 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	combinederr = MonitorCRs(testConductor, duration, "")
It looks like this will run after that the other tests have finished. If you want to run this function it should be in a go routine so that it runs in parallel with primitivePoolDeletion(). See non_steady_state.go test_volumes() to see how to run MonitorCR()s in a go routine and capture errors in a "chan".
You don't have to put primitivePoolDeletion() into a go routine as well, but either it or MonitorCRs() should be in a go routine so they can run in parallel.
OTOH maybe MonitorCRs() is not needed here as the function is intended for "happy path" tests.

2022-02-24 08:12 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	err = k8stest.RestartMayastorPods(params.MayastorRestartTimeout)
I don't think this call will work. The functions in "mayastor-e2e/common/k8stest" are written to be run outside of the cluster. This RestartMayastorPods() will be called from within the cluster so needs a version of this function in extended-test-framework/common/k8sclient.

2022-02-24 14:37 UTC, rohan2794 commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	combinederr = MonitorCRs(testConductor, duration, "")
Thanks, 
Done

2022-02-24 14:37 UTC, rohan2794 commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +
Done

2022-02-24 14:37 UTC, rohan2794 commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +		return fmt.Errorf("failed to get mayastor pool usage in cluster, error: %v", err)
Done

2022-02-24 14:37 UTC, rohan2794 commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	if err != nil {
Done

2022-02-25 12:39 UTC, chriswldenyer requested changes
Some more changes needed it looks like. It could also do with descriptions of the stages.

2022-02-25 12:39 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +				return fmt.Errorf("failed to create pool %s via gRPC, error: %v", mayastorPool.Name, err)
Should the error message be "failed to create replica" ?

2022-02-25 12:39 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	var combinederr error
Comparing with primitive_msp_deletion test it looks like you are missing some steps, removing replicas, checking for zero replicas, and checking pool usage is zero.

2022-02-25 14:44 UTC, rohan2794 commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	} else if poolUsage != 0 {
yes, well spotted

2022-02-28 07:45 UTC, chriswldenyer approved these changes
LGTM but some suggested simplifications.

2022-02-28 07:45 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	timeoutSec, err := time.ParseDuration(params.ReplicasTimeoutSecs)
(here and other places) I think you could do time.ParseDuration() once for each of durations in params and store them at the top of the function as replicaTimeoutSec, poolUsageTimeoutSec etc. That way you will avoid duplicating time.ParseDuration and the error handling in this function.

2022-02-28 07:45 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +		} else if poolUsage != 0 {
(here and other places) you could return "return fmt.Errorf("failed to get mayastor pool usage in cluster, error: %v", err)" after line 125 insteadof line 132 which would avoid having to re-check err

2022-02-28 10:04 UTC, chriswldenyer commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +		} else if poolUsage != 0 {
Ignore my last comment - it's fine!

2022-02-28 10:50 UTC, milanhajek approved these changes

2022-02-28 10:51 UTC, rohan2794 commented on src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
> +	timeoutSec, err := time.ParseDuration(params.ReplicasTimeoutSecs)
Done

2022-02-28 10:53 UTC, chriswldenyer approved these changes
LGTM

2022-02-28 11:35 UTC, rohan2794 commented
bors merge

2022-02-28 12:08 UTC, merged